application:
  name: ^project.artifactId^
  description: ^project.name^
  version: ^project.version^
eureka.instance.preferIpAddress: true
spring:
  application:
    name: ^project.artifactId^
  main:
    banner-mode: "off"