server:
  port: 80
application:
  name: ^project.artifactId^
  description: ^project.name^
  version: ^project.version^
spring:
  application:
    name: ^project.artifactId^
  main:
    banner-mode: "off"
eureka:
  instance:
    hostname: softwok-alb-1936994770.us-east-1.elb.amazonaws.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/